### ISSUE TITLE
Nodejs models

### ISSUE THREAD

**Issue by AmanBansal1998** [paazmaya/image-duplicate-remover#21]
### Expected behaviour

What it should have accomplished.

### Actual behaviour

How to reproduce with minimal working example.

### Versions and environment

 * Operating system:
 * Command line tool:
 * Node.js:
 * npm:
 * image-duplicate-remover:

Thank you and have some :beers:.

**Comment by paazmaya** [comment]
@AmanBansal1998 what are you referring to? Please write more details in the description.
